In [53]:
import os

import pandas as pd 

path = '../data/raw' 

circuit_economics_data = pd.read_csv(os.path.join(path, 'circuit_economics.csv'))
constructor_finances_data = pd.read_csv(os.path.join(path, 'constructor_finances.csv'))
driver_standings_data = pd.read_csv(os.path.join(path, 'driver_standings.csv'))
race_results_data = pd.read_csv(os.path.join(path, 'race_results.csv'))
f_one_business_data = pd.read_csv(os.path.join(path, 'f1_business.csv'))


tables = [circuit_economics_data, constructor_finances_data, driver_standings_data, race_results_data, f_one_business_data]

for i in range(1, len(tables)):
    
    df = tables[i]
    print(f"#{i}: \n {df.head()}")

#1:
    season team_name country_iso3  operating_budget_usd_m  \
0    2010  Mercedes          DEU                   270.0
1    2011  Mercedes          DEU                   320.5
2    2012  Mercedes          DEU                   308.3
3    2013  Mercedes          DEU                   356.9
4    2014  Mercedes          DEU                   339.4

   sponsorship_revenue_usd_m  prize_money_usd_m  total_revenue_usd_m  \
0                       86.2              112.6                198.8
1                      100.2              118.4                218.6
2                      102.4              130.4                232.9
3                      126.9              158.6                285.6
4                      128.8              173.6                302.3

   in_cost_cap_era  cost_cap_limit_usd_m  is_constructors_champion
0                0                   NaN                         0
1                0                   NaN                         0
2                0                   NaN                         0
3                0                   NaN                         0
4                0                   NaN                         1
#2:
    season  championship_position       driver_name country_iso3  total_points  \
0    2010                      1  Sebastian Vettel          DEU           256
1    2010                      2   Fernando Alonso          ESP           252
2    2010                      3       Mark Webber          AUS           242
3    2010                      4    Lewis Hamilton          GBR           240
4    2010                      5     Jenson Button          GBR           214

   wins  poles  podiums_est  is_world_champion
0     5     10            9                  1
1     5      2            9                  0
2     4      5            8                  0
3     3      1            7                  0
4     2      0            5                  0
#3:
   race_id  season  round_number   race_date grand_prix      circuit  \
0    R001    2010             1  2010-03-21    Bahrain       Sakhir
1    R002    2010             2  2010-03-15  Australia  Albert Park
2    R003    2010             3  2010-04-10   Malaysia       Sepang
3    R004    2010             4  2010-04-03      China     Shanghai
4    R005    2010             5  2010-05-19      Spain    Barcelona

  country_iso3       region     pole_position           winner  \
0          BHR  Middle East     Robert Kubica   Lewis Hamilton
1          AUS      Oceania  Sebastian Vettel  Fernando Alonso
2          MYS         Asia  Sebastian Vettel    Jenson Button
3          CHN         Asia  Sebastian Vettel  Fernando Alonso
4          ESP       Europe       Mark Webber      Mark Webber

        podium_p2         podium_p3 fastest_lap_driver  safety_car_periods  \
0     Mark Webber     Oscar Piastri      Oscar Piastri                   0
1     Mark Webber   Valtteri Bottas   Daniel Ricciardo                   1
2    Lando Norris     Oscar Piastri       Lando Norris                   1
3  Lewis Hamilton  Daniel Ricciardo    Fernando Alonso                   0
4  Lewis Hamilton   Fernando Alonso     Lewis Hamilton                   1

   is_sprint_weekend
0                  0
1                  0
2                  0
3                  0
4                  0
#4:
    season  total_revenue_usd_m  race_promotion_fees_usd_m  \
0    2010               1108.0                      399.0
1    2011               1265.0                      455.0
2    2012               1377.0                      496.0
3    2013               1509.0                      543.0
4    2014               1728.0                      622.0

   broadcast_media_usd_m  sponsorship_usd_m  other_revenue_usd_m  \
0                  377.0              177.0                155.0
1                  430.0              202.0                177.0
2                  468.0              220.0                193.0
3                  513.0              241.0                211.0
4                  588.0              276.0                242.0

   is_liberty_media_era  drive_to_survive_viewers_m_est  \
0                     0                               0
1                     0                               0
2                     0                               0
3                     0                               0
4                     0                               0

   us_avg_race_viewers_m  global_avg_race_viewers_m
0                   0.55                       70.0
1                   0.55                       71.5
2                   0.55                       73.0
3                   0.55                       74.5
4                   0.55                       76.0

In [54]:
df_names = ["Circuit Economics", "Constructor Finances", "Driver Standings", "Race Results", "F1 Business"]

for name, df in zip(df_names, tables):
    print(f"\n--- {name} ---")
    print(f"Shape: {df.shape}")
    print(f"DTypes: \n {df.dtypes}")
    print(f"Missing values: {df.isna().sum()[df.isna().sum() > 0]}")
    print(f"Duplicates: {df.duplicated().sum()}")

--- Circuit Economics ---
Shape: (277, 10)
DTypes:
 season                        int64
grand_prix                      str
circuit                         str
country_iso3                    str
region                          str
hosting_fee_usd_m_est       float64
weekend_attendance_k          int64
debut_year                    int64
is_street_circuit             int64
is_new_circuit_post_2020      int64
dtype: object
Missing values: Series([], dtype: int64)
Duplicates: 0

--- Constructor Finances ---
Shape: (164, 10)
DTypes:
 season                         int64
team_name                        str
country_iso3                     str
operating_budget_usd_m       float64
sponsorship_revenue_usd_m    float64
prize_money_usd_m            float64
total_revenue_usd_m          float64
in_cost_cap_era                int64
cost_cap_limit_usd_m         float64
is_constructors_champion       int64
dtype: object
Missing values: cost_cap_limit_usd_m    104
dtype: int64
Duplicates: 0

--- Driver Standings ---
Shape: (107, 9)
DTypes:
 season                   int64
championship_position    int64
driver_name                str
country_iso3               str
total_points             int64
wins                     int64
poles                    int64
podiums_est              int64
is_world_champion        int64
dtype: object
Missing values: Series([], dtype: int64)
Duplicates: 0

--- Race Results ---
Shape: (337, 15)
DTypes:
 race_id                 str
season                int64
round_number          int64
race_date               str
grand_prix              str
circuit                 str
country_iso3            str
region                  str
pole_position           str
winner                  str
podium_p2               str
podium_p3               str
fastest_lap_driver      str
safety_car_periods    int64
is_sprint_weekend     int64
dtype: object
Missing values: Series([], dtype: int64)
Duplicates: 0

--- F1 Business ---
Shape: (17, 10)
DTypes:
 season                              int64
total_revenue_usd_m               float64
race_promotion_fees_usd_m         float64
broadcast_media_usd_m             float64
sponsorship_usd_m                 float64
other_revenue_usd_m               float64
is_liberty_media_era                int64
drive_to_survive_viewers_m_est      int64
us_avg_race_viewers_m             float64
global_avg_race_viewers_m         float64
dtype: object
Missing values: Series([], dtype: int64)
Duplicates: 0

In [55]:
data_dict = {key: value for key, value in zip(df_names, tables)}
print(data_dict)

{'Circuit Economics':      season grand_prix     circuit country_iso3       region  \
0      2010    Bahrain      Sakhir          BHR  Middle East
1      2012    Bahrain      Sakhir          BHR  Middle East
2      2013    Bahrain      Sakhir          BHR  Middle East
3      2014    Bahrain      Sakhir          BHR  Middle East
4      2015    Bahrain      Sakhir          BHR  Middle East
..      ...        ...         ...          ...          ...
272    2021  Abu Dhabi  Yas Marina          ARE  Middle East
273    2022  Abu Dhabi  Yas Marina          ARE  Middle East
274    2023  Abu Dhabi  Yas Marina          ARE  Middle East
275    2024  Abu Dhabi  Yas Marina          ARE  Middle East
276    2025  Abu Dhabi  Yas Marina          ARE  Middle East

     hosting_fee_usd_m_est  weekend_attendance_k  debut_year  \
0                     38.5                    97        2004
1                     35.8                   100        2004
2                     34.6                    94        2004
3                     35.1                    96        2004
4                     34.2                    94        2004
..                     ...                   ...         ...
272                   30.9                    70        2009
273                   37.3                   149        2009
274                   34.5                   152        2009
275                   34.3                   153        2009
276                   34.6                   156        2009

     is_street_circuit  is_new_circuit_post_2020
0                    0                         0
1                    0                         0
2                    0                         0
3                    0                         0
4                    0                         0
..                 ...                       ...
272                  0                         0
273                  0                         0
274                  0                         0
275                  0                         0
276                  0                         0

[277 rows x 10 columns], 'Constructor Finances':      season team_name country_iso3  operating_budget_usd_m  \
0      2010  Mercedes          DEU                   270.0
1      2011  Mercedes          DEU                   320.5
2      2012  Mercedes          DEU                   308.3
3      2013  Mercedes          DEU                   356.9
4      2014  Mercedes          DEU                   339.4
..      ...       ...          ...                     ...
159    2022      Haas          USA                   125.7
160    2023      Haas          USA                   140.7
161    2024      Haas          USA                   147.2
162    2025      Haas          USA                   150.5
163    2026      Haas          USA                   165.5

     sponsorship_revenue_usd_m  prize_money_usd_m  total_revenue_usd_m  \
0                         86.2              112.6                198.8
1                        100.2              118.4                218.6
2                        102.4              130.4                232.9
3                        126.9              158.6                285.6
4                        128.8              173.6                302.3
..                         ...                ...                  ...
159                       86.5               51.6                138.1
160                      103.4               53.8                157.3
161                      118.8               62.6                181.4
162                      131.6               80.1                211.8
163                      146.8               73.2                220.0

     in_cost_cap_era  cost_cap_limit_usd_m  is_constructors_champion
0                  0                   NaN                         0
1                  0                   NaN                         0
2                  0                   NaN                         0
3                  0                   NaN                         0
4                  0                   NaN                         1
..               ...                   ...                       ...
159                1                 140.0                         0
160                1                 135.0                         0
161                1                 135.0                         0
162                1                 135.0                         0
163                1                 130.0                         0

[164 rows x 10 columns], 'Driver Standings':      season  championship_position       driver_name country_iso3  \
0      2010                      1  Sebastian Vettel          DEU
1      2010                      2   Fernando Alonso          ESP
2      2010                      3       Mark Webber          AUS
3      2010                      4    Lewis Hamilton          GBR
4      2010                      5     Jenson Button          GBR
..      ...                    ...               ...          ...
102    2026                      2     Oscar Piastri          AUS
103    2026                      3    Max Verstappen          NLD
104    2026                      4   Charles Leclerc          MCO
105    2026                      5    George Russell          GBR
106    2026                      6    Lewis Hamilton          GBR

     total_points  wins  poles  podiums_est  is_world_champion
0             256     5     10            9                  1
1             252     5      2            9                  0
2             242     4      5            8                  0
3             240     3      1            7                  0
4             214     2      0            5                  0
..            ...   ...    ...          ...                ...
102            75     1      2            2                  0
103            72     2      1            3                  0
104            65     1      2            2                  0
105            48     1      0            1                  0
106            35     1      0            1                  0

[107 rows x 9 columns], 'Race Results':     race_id  season  round_number   race_date      grand_prix      circuit  \
0      R001    2010             1  2010-03-21         Bahrain       Sakhir
1      R002    2010             2  2010-03-15       Australia  Albert Park
2      R003    2010             3  2010-04-10        Malaysia       Sepang
3      R004    2010             4  2010-04-03           China     Shanghai
4      R005    2010             5  2010-05-19           Spain    Barcelona
..      ...     ...           ...         ...             ...          ...
332    R333    2026             4  2026-06-17         Bahrain       Sakhir
333    R334    2026             5  2026-08-14    Saudi Arabia       Jeddah
334    R335    2026             6  2026-09-22           Miami   Miami Intl
335    R336    2026             7  2026-10-13  Emilia-Romagna        Imola
336    R337    2026             8  2026-12-09          Monaco  Monte Carlo

    country_iso3         region     pole_position           winner  \
0            BHR    Middle East     Robert Kubica   Lewis Hamilton
1            AUS        Oceania  Sebastian Vettel  Fernando Alonso
2            MYS           Asia  Sebastian Vettel    Jenson Button
3            CHN           Asia  Sebastian Vettel  Fernando Alonso
4            ESP         Europe       Mark Webber      Mark Webber
..           ...            ...               ...              ...
332          BHR    Middle East      Lando Norris    Oscar Piastri
333          SAU    Middle East     Oscar Piastri   George Russell
334          USA  North America      Lando Norris   Max Verstappen
335          ITA         Europe   Charles Leclerc     Lando Norris
336          MCO         Europe   Charles Leclerc   Max Verstappen

           podium_p2         podium_p3 fastest_lap_driver  safety_car_periods  \
0        Mark Webber     Oscar Piastri      Oscar Piastri                   0
1        Mark Webber   Valtteri Bottas   Daniel Ricciardo                   1
2       Lando Norris     Oscar Piastri       Lando Norris                   1
3     Lewis Hamilton  Daniel Ricciardo    Fernando Alonso                   0
4     Lewis Hamilton   Fernando Alonso     Lewis Hamilton                   1
..               ...               ...                ...                 ...
332  Charles Leclerc      Sergio Perez    Fernando Alonso                   1
333  Charles Leclerc   Fernando Alonso    Fernando Alonso                   0
334  Charles Leclerc   Valtteri Bottas   Daniel Ricciardo                   2
335   Max Verstappen    George Russell    Fernando Alonso                   1
336    Oscar Piastri     Oscar Piastri   Daniel Ricciardo                   1

     is_sprint_weekend
0                    0
1                    0
2                    0
3                    0
4                    0
..                 ...
332                  0
333                  0
334                  0
335                  0
336                  0

[337 rows x 15 columns], 'F1 Business':     season  total_revenue_usd_m  race_promotion_fees_usd_m  \
0     2010               1108.0                      399.0
1     2011               1265.0                      455.0
2     2012               1377.0                      496.0
3     2013               1509.0                      543.0
4     2014               1728.0                      622.0
5     2015               1731.0                      623.0
6     2016               1805.0                      650.0
7     2017               1835.0                      660.0
8     2018               1806.0                      650.0
9     2019               2022.0                      728.0
10    2020                766.0                      424.0
11    2021               2160.0                      778.0
12    2022               2486.0                      895.0
13    2023               3208.0                     1155.0
14    2024               3782.0                     1362.0
15    2025               3933.0                     1416.0
16    2026               4051.0                     1459.0

    broadcast_media_usd_m  sponsorship_usd_m  other_revenue_usd_m  \
0                   377.0              177.0                155.0
1                   430.0              202.0                177.0
2                   468.0              220.0                193.0
3                   513.0              241.0                211.0
4                   588.0              276.0                242.0
5                   588.0              277.0                242.0
6                   614.0              289.0                253.0
7                   624.0              294.0                257.0
8                   614.0              289.0                253.0
9                   688.0              324.0                283.0
10                  401.0              189.0                165.0
11                  734.0              346.0                302.0
12                  845.0              398.0                348.0
13                 1091.0              513.0                449.0
14                 1286.0              605.0                530.0
15                 1337.0              629.0                551.0
16                 1377.0              648.0                567.0

    is_liberty_media_era  drive_to_survive_viewers_m_est  \
0                      0                               0
1                      0                               0
2                      0                               0
3                      0                               0
4                      0                               0
5                      0                               0
6                      0                               0
7                      1                               0
8                      1                               0
9                      1                               0
10                     1                              13
11                     1                              25
12                     1                              50
13                     1                              85
14                     1                              60
15                     1                              45
16                     1                              30

    us_avg_race_viewers_m  global_avg_race_viewers_m
0                    0.55                       70.0
1                    0.55                       71.5
2                    0.55                       73.0
3                    0.55                       74.5
4                    0.55                       76.0
5                    0.55                       77.5
6                    0.55                       79.0
7                    0.55                       80.5
8                    0.55                       82.0
9                    0.60                       83.5
10                   0.55                       72.2
11                   0.95                       91.5
12                   1.21                       88.0
13                   1.11                       89.5
14                   1.10                       91.0
15                   1.30                       92.5
16                   1.45                       94.0  }

In [56]:
constructor_df = pd.DataFrame(data_dict['Constructor Finances'])

number_of_teams = constructor_df['team_name'].nunique()
print("# of Teams: \n", number_of_teams)

# of Teams:
 10

In [57]:
number_of_teams_by_season = constructor_df.groupby('season')['team_name'].nunique()
print("# of Teams by Season: \n", number_of_teams_by_season)

# of Teams by Season:
 season
2010     9
2011     9
2012     9
2013     9
2014     9
2015     9
2016    10
2017    10
2018    10
2019    10
2020    10
2021    10
2022    10
2023    10
2024    10
2025    10
2026    10
Name: team_name, dtype: int64

In [58]:
duplicate_teams_season = constructor_df.duplicated(subset=["team_name", "season"])
print("Duplicates: \n", duplicate_teams_season)

total = duplicate_teams_season.sum()
print("# of duplicates: \n", total)

Duplicates:
 0      False
1      False
2      False
3      False
4      False
       ...
159    False
160    False
161    False
162    False
163    False
Length: 164, dtype: bool
# of duplicates:
 0

In [59]:
constructor_df

,season,team_name,country_iso3,operating_budget_usd_m,sponsorship_revenue_usd_m,prize_money_usd_m,total_revenue_usd_m,in_cost_cap_era,cost_cap_limit_usd_m,is_constructors_champion
0,2010,Mercedes,DEU,270.0,86.2,112.6,198.8,0,NaN,0
1,2011,Mercedes,DEU,320.5,100.2,118.4,218.6,0,NaN,0
2,2012,Mercedes,DEU,308.3,102.4,130.4,232.9,0,NaN,0
3,2013,Mercedes,DEU,356.9,126.9,158.6,285.6,0,NaN,0
4,2014,Mercedes,DEU,339.4,128.8,173.6,302.3,0,NaN,1
...,...,...,...,...,...,...,...,...,...,...
159,2022,Haas,USA,125.7,86.5,51.6,138.1,1,140.0,0
160,2023,Haas,USA,140.7,103.4,53.8,157.3,1,135.0,0
161,2024,Haas,USA,147.2,118.8,62.6,181.4,1,135.0,0
162,2025,Haas,USA,150.5,131.6,80.1,211.8,1,135.0,0
163,2026,Haas,USA,165.5,146.8,73.2,220.0,1,130.0,0

In [60]:
constructor_df.isna().sum()

season                         0
team_name                      0
country_iso3                   0
operating_budget_usd_m         0
sponsorship_revenue_usd_m      0
prize_money_usd_m              0
total_revenue_usd_m            0
in_cost_cap_era                0
cost_cap_limit_usd_m         104
is_constructors_champion       0
dtype: int64

In [61]:
cost_cap_with_values = constructor_df.loc[constructor_df["cost_cap_limit_usd_m"] >= 0, ["season", "cost_cap_limit_usd_m"]].sort_values("season")
cost_cap_with_values

     season  cost_cap_limit_usd_m
11     2021                 145.0
28     2021                 145.0
45     2021                 145.0
62     2021                 145.0
79     2021                 145.0
96     2021                 145.0
130    2021                 145.0
113    2021                 145.0
147    2021                 145.0
158    2021                 145.0
97     2022                 140.0
80     2022                 140.0
63     2022                 140.0
12     2022                 140.0
46     2022                 140.0
29     2022                 140.0
114    2022                 140.0
131    2022                 140.0
159    2022                 140.0
148    2022                 140.0
149    2023                 135.0
160    2023                 135.0
132    2023                 135.0
98     2023                 135.0
81     2023                 135.0
64     2023                 135.0
13     2023                 135.0
115    2023                 135.0
47     2023                 135.0
30     2023                 135.0
31     2024                 135.0
65     2024                 135.0
161    2024                 135.0
150    2024                 135.0
14     2024                 135.0
48     2024                 135.0
82     2024                 135.0
133    2024                 135.0
116    2024                 135.0
99     2024                 135.0
32     2025                 135.0
15     2025                 135.0
162    2025                 135.0
151    2025                 135.0
100    2025                 135.0
49     2025                 135.0
66     2025                 135.0
83     2025                 135.0
117    2025                 135.0
134    2025                 135.0
84     2026                 130.0
33     2026                 130.0
16     2026                 130.0
67     2026                 130.0
50     2026                 130.0
101    2026                 130.0
135    2026                 130.0
118    2026                 130.0
152    2026                 130.0
163    2026                 130.0

In [62]:
f_one_business_df = pd.DataFrame(data_dict["F1 Business"])
# f_one_business_df.groupby('season').nunique()
f_one_business_df

,season,total_revenue_usd_m,race_promotion_fees_usd_m,broadcast_media_usd_m,sponsorship_usd_m,other_revenue_usd_m,is_liberty_media_era,drive_to_survive_viewers_m_est,us_avg_race_viewers_m,global_avg_race_viewers_m
0,2010,1108.0,399.0,377.0,177.0,155.0,0,0,0.55,70.0
1,2011,1265.0,455.0,430.0,202.0,177.0,0,0,0.55,71.5
2,2012,1377.0,496.0,468.0,220.0,193.0,0,0,0.55,73.0
3,2013,1509.0,543.0,513.0,241.0,211.0,0,0,0.55,74.5
4,2014,1728.0,622.0,588.0,276.0,242.0,0,0,0.55,76.0
5,2015,1731.0,623.0,588.0,277.0,242.0,0,0,0.55,77.5
6,2016,1805.0,650.0,614.0,289.0,253.0,0,0,0.55,79.0
7,2017,1835.0,660.0,624.0,294.0,257.0,1,0,0.55,80.5
8,2018,1806.0,650.0,614.0,289.0,253.0,1,0,0.55,82.0
9,2019,2022.0,728.0,688.0,324.0,283.0,1,0,0.60,83.5
10,2020,766.0,424.0,401.0,189.0,165.0,1,13,0.55,72.2
11,2021,2160.0,778.0,734.0,346.0,302.0,1,25,0.95,91.5
12,2022,2486.0,895.0,845.0,398.0,348.0,1,50,1.21,88.0
13,2023,3208.0,1155.0,1091.0,513.0,449.0,1,85,1.11,89.5
14,2024,3782.0,1362.0,1286.0,605.0,530.0,1,60,1.10,91.0
15,2025,3933.0,1416.0,1337.0,629.0,551.0,1,45,1.30,92.5
16,2026,4051.0,1459.0,1377.0,648.0,567.0,1,30,1.45,94.0

In [63]:
f1_business_season_uniqueness_check = f_one_business_df.groupby("season").nunique()

f1_business_season_uniqueness_check

,total_revenue_usd_m,race_promotion_fees_usd_m,broadcast_media_usd_m,sponsorship_usd_m,other_revenue_usd_m,is_liberty_media_era,drive_to_survive_viewers_m_est,us_avg_race_viewers_m,global_avg_race_viewers_m
season,,,,,,,,,
2010,1,1,1,1,1,1,1,1,1
2011,1,1,1,1,1,1,1,1,1
2012,1,1,1,1,1,1,1,1,1
2013,1,1,1,1,1,1,1,1,1
2014,1,1,1,1,1,1,1,1,1
2015,1,1,1,1,1,1,1,1,1
2016,1,1,1,1,1,1,1,1,1
2017,1,1,1,1,1,1,1,1,1
2018,1,1,1,1,1,1,1,1,1
2019,1,1,1,1,1,1,1,1,1
2020,1,1,1,1,1,1,1,1,1
2021,1,1,1,1,1,1,1,1,1
2022,1,1,1,1,1,1,1,1,1
2023,1,1,1,1,1,1,1,1,1
2024,1,1,1,1,1,1,1,1,1
2025,1,1,1,1,1,1,1,1,1
2026,1,1,1,1,1,1,1,1,1

In [64]:
champions = constructor_df.loc[constructor_df["is_constructors_champion"] == 1, ["season", "team_name"],].sort_values("season")
champions

    season team_name
4     2014  Mercedes
5     2015  Mercedes
6     2016  Mercedes
7     2017  Mercedes
8     2018  Mercedes
9     2019  Mercedes
10    2020  Mercedes
11    2021  Mercedes
65    2024   McLaren
66    2025   McLaren

In [65]:
teams = constructor_df.groupby("team_name").nunique()

# seasons_without_winner = champions_per_season[champions_per_season == 0].index

teams

,season,country_iso3,operating_budget_usd_m,sponsorship_revenue_usd_m,prize_money_usd_m,total_revenue_usd_m,in_cost_cap_era,cost_cap_limit_usd_m,is_constructors_champion
team_name,,,,,,,,,
Alpine,17,1,17,17,17,17,2,4,1
Aston Martin,17,1,17,17,17,17,2,4,1
Ferrari,17,1,17,17,17,17,2,4,1
Haas,11,1,11,11,11,11,2,4,1
McLaren,17,1,17,17,17,17,2,4,2
Mercedes,17,1,17,17,17,17,2,4,2
RB (AlphaTauri),17,1,17,17,17,17,2,4,1
Red Bull Racing,17,1,17,17,17,16,2,4,1
Stake (Sauber),17,1,17,17,17,17,2,4,1
Williams,17,1,17,17,17,17,2,4,1

In [66]:
champions_per_season = constructor_df.groupby("season")["is_constructors_champion"].sum()

seasons_without_winner = champions_per_season[champions_per_season == 0].index

seasons_without_winner

Index([2010, 2011, 2012, 2013, 2022, 2023, 2026], dtype='int64', name='season')

In [67]:
no_winner_rows = constructor_df[constructor_df["season"].isin(seasons_without_winner)]

no_winner_rows[["season", "operating_budget_usd_m", "is_constructors_champion"]]

     season  operating_budget_usd_m  is_constructors_champion
0      2010                   270.0                         0
1      2011                   320.5                         0
2      2012                   308.3                         0
3      2013                   356.9                         0
12     2022                   424.9                         0
..      ...                     ...                       ...
149    2023                   146.5                         0
152    2026                   178.9                         0
159    2022                   125.7                         0
160    2023                   140.7                         0
163    2026                   165.5                         0

[66 rows x 3 columns]

In [68]:
aston_martin_before_2021 = constructor_df.loc[constructor_df["team_name"] == "Aston Martin"]

aston_martin_before_2021

,season,team_name,country_iso3,operating_budget_usd_m,sponsorship_revenue_usd_m,prize_money_usd_m,total_revenue_usd_m,in_cost_cap_era,cost_cap_limit_usd_m,is_constructors_champion
68,2010,Aston Martin,GBR,77.3,30.3,30.0,60.3,0,NaN,0
69,2011,Aston Martin,GBR,88.7,33.8,34.8,68.6,0,NaN,0
70,2012,Aston Martin,GBR,87.7,40.3,40.9,81.2,0,NaN,0
71,2013,Aston Martin,GBR,101.3,41.5,47.3,88.8,0,NaN,0
72,2014,Aston Martin,GBR,112.0,48.2,49.3,97.5,0,NaN,0
73,2015,Aston Martin,GBR,108.2,57.0,51.9,108.9,0,NaN,0
74,2016,Aston Martin,GBR,131.1,67.8,58.5,126.3,0,NaN,0
75,2017,Aston Martin,GBR,126.5,81.0,59.6,140.6,0,NaN,0
76,2018,Aston Martin,GBR,153.2,94.1,66.2,160.4,0,NaN,0
77,2019,Aston Martin,GBR,152.4,110.4,78.3,188.6,0,NaN,0
78,2020,Aston Martin,GBR,183.7,127.0,107.0,234.0,0,NaN,0
79,2021,Aston Martin,GBR,183.4,156.6,80.3,236.9,1,145.0,0
80,2022,Aston Martin,GBR,214.6,181.3,66.8,248.0,1,140.0,0
81,2023,Aston Martin,GBR,247.9,231.0,100.2,331.2,1,135.0,0
82,2024,Aston Martin,GBR,273.5,252.6,128.9,381.6,1,135.0,0
83,2025,Aston Martin,GBR,272.0,227.6,142.0,369.6,1,135.0,0
84,2026,Aston Martin,GBR,288.4,256.7,145.9,402.6,1,130.0,0

In [69]:
driver_standings_df = pd.DataFrame(data_dict["Driver Standings"])
driver_standings_df.groupby('season')['driver_name'].nunique()
# driver_standings_df

season
2010    8
2011    6
2012    6
2013    6
2014    6
2015    6
2016    6
2017    6
2018    6
2019    6
2020    6
2021    6
2022    6
2023    6
2024    8
2025    7
2026    6
Name: driver_name, dtype: int64

In [70]:
circuit_econs_df = pd.DataFrame(data_dict["Circuit Economics"])
circuit_econs_df

,season,grand_prix,circuit,country_iso3,region,hosting_fee_usd_m_est,weekend_attendance_k,debut_year,is_street_circuit,is_new_circuit_post_2020
0,2010,Bahrain,Sakhir,BHR,Middle East,38.5,97,2004,0,0
1,2012,Bahrain,Sakhir,BHR,Middle East,35.8,100,2004,0,0
2,2013,Bahrain,Sakhir,BHR,Middle East,34.6,94,2004,0,0
3,2014,Bahrain,Sakhir,BHR,Middle East,35.1,96,2004,0,0
4,2015,Bahrain,Sakhir,BHR,Middle East,34.2,94,2004,0,0
...,...,...,...,...,...,...,...,...,...,...
272,2021,Abu Dhabi,Yas Marina,ARE,Middle East,30.9,70,2009,0,0
273,2022,Abu Dhabi,Yas Marina,ARE,Middle East,37.3,149,2009,0,0
274,2023,Abu Dhabi,Yas Marina,ARE,Middle East,34.5,152,2009,0,0
275,2024,Abu Dhabi,Yas Marina,ARE,Middle East,34.3,153,2009,0,0
276,2025,Abu Dhabi,Yas Marina,ARE,Middle East,34.6,156,2009,0,0

In [71]:
race_results_df = pd.DataFrame(data_dict["Race Results"])
race_results_df

,race_id,season,round_number,race_date,grand_prix,circuit,country_iso3,region,pole_position,winner,podium_p2,podium_p3,fastest_lap_driver,safety_car_periods,is_sprint_weekend
0,R001,2010,1,2010-03-21,Bahrain,Sakhir,BHR,Middle East,Robert Kubica,Lewis Hamilton,Mark Webber,Oscar Piastri,Oscar Piastri,0,0
1,R002,2010,2,2010-03-15,Australia,Albert Park,AUS,Oceania,Sebastian Vettel,Fernando Alonso,Mark Webber,Valtteri Bottas,Daniel Ricciardo,1,0
2,R003,2010,3,2010-04-10,Malaysia,Sepang,MYS,Asia,Sebastian Vettel,Jenson Button,Lando Norris,Oscar Piastri,Lando Norris,1,0
3,R004,2010,4,2010-04-03,China,Shanghai,CHN,Asia,Sebastian Vettel,Fernando Alonso,Lewis Hamilton,Daniel Ricciardo,Fernando Alonso,0,0
4,R005,2010,5,2010-05-19,Spain,Barcelona,ESP,Europe,Mark Webber,Mark Webber,Lewis Hamilton,Fernando Alonso,Lewis Hamilton,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332,R333,2026,4,2026-06-17,Bahrain,Sakhir,BHR,Middle East,Lando Norris,Oscar Piastri,Charles Leclerc,Sergio Perez,Fernando Alonso,1,0
333,R334,2026,5,2026-08-14,Saudi Arabia,Jeddah,SAU,Middle East,Oscar Piastri,George Russell,Charles Leclerc,Fernando Alonso,Fernando Alonso,0,0
334,R335,2026,6,2026-09-22,Miami,Miami Intl,USA,North America,Lando Norris,Max Verstappen,Charles Leclerc,Valtteri Bottas,Daniel Ricciardo,2,0
335,R336,2026,7,2026-10-13,Emilia-Romagna,Imola,ITA,Europe,Charles Leclerc,Lando Norris,Max Verstappen,George Russell,Fernando Alonso,1,0
336,R337,2026,8,2026-12-09,Monaco,Monte Carlo,MCO,Europe,Charles Leclerc,Max Verstappen,Oscar Piastri,Oscar Piastri,Daniel Ricciardo,1,0

## Checks backing NOTES.md
Each cell below backs a claim in `NOTES.md`. The section is named in the cell's heading.

### Q2. `season` is unique in `f1_business`
`groupby().nunique()` (cell above) shows 1 per column even if a season appears twice with identical values, so count rows per season directly.

In [72]:
rows_per_season = f_one_business_df["season"].value_counts()

print("# of rows: ", len(f_one_business_df))
print("# of unique seasons: ", f_one_business_df["season"].nunique())
print("Seasons with more than one row: ", rows_per_season[rows_per_season > 1].index.tolist())

# of rows:  17
# of unique seasons:  17
Seasons with more than one row:  []

### Q1. Missing values in `cost_cap_limit_usd_m` are all before the cost cap era

In [73]:
missing_cost_cap = constructor_df.loc[constructor_df["cost_cap_limit_usd_m"].isna()]

print("# of missing values: ", len(missing_cost_cap))
print("Seasons with missing values: ", missing_cost_cap["season"].min(), "-", missing_cost_cap["season"].max())
print("Missing values inside the cost cap era: ", (missing_cost_cap["in_cost_cap_era"] == 1).sum())

# of missing values:  104
Seasons with missing values:  2010 - 2020
Missing values inside the cost cap era:  0

### Q2. Excluded tables have no team column

In [74]:
for name in ["Race Results", "Driver Standings", "Circuit Economics"]:
    team_columns = [col for col in data_dict[name].columns if "team" in col or "constructor" in col]
    print(f"{name}: {team_columns}")

Race Results: []
Driver Standings: []
Circuit Economics: []

### Q2. Races per season (size of a season-only join)

In [75]:
races_per_season = race_results_df.groupby("season")["race_id"].nunique()
races_per_season

season
2010    19
2011    19
2012    20
2013    19
2014    19
2015    19
2016    21
2017    20
2018    21
2019    21
2020    17
2021    22
2022    22
2023    22
2024    24
2025    24
2026     8
Name: race_id, dtype: int64

### Q3, Finding 4. `race_results` has impossible entries
Real 2010 Bahrain GP: Fernando Alonso won. Oscar Piastri debuted in 2023.

In [76]:
race_results_df.loc[(race_results_df["season"] == 2010) & (race_results_df["grand_prix"] == "Bahrain"), ["season", "grand_prix", "winner", "podium_p2", "podium_p3"]]

   season grand_prix          winner    podium_p2      podium_p3
0    2010    Bahrain  Lewis Hamilton  Mark Webber  Oscar Piastri

### Q4 / Q5. Team revenue = sponsorship + prize money

In [77]:
revenue_difference = (constructor_df["sponsorship_revenue_usd_m"] + constructor_df["prize_money_usd_m"] - constructor_df["total_revenue_usd_m"]).abs()

print("Largest difference: ", round(revenue_difference.max(), 2))
print("# of rows off by more than rounding (0.15): ", (revenue_difference > 0.15).sum())

Largest difference:  0.1
# of rows off by more than rounding (0.15):  0

### Q4. Cost cap per season
Real base cap: 145 (2021), 140 (2022), 135 (2023-2025), about 215 (2026, verify).

In [78]:
constructor_df.groupby("season")["cost_cap_limit_usd_m"].unique()

season
2010      [nan]
2011      [nan]
2012      [nan]
2013      [nan]
2014      [nan]
2015      [nan]
2016      [nan]
2017      [nan]
2018      [nan]
2019      [nan]
2020      [nan]
2021    [145.0]
2022    [140.0]
2023    [135.0]
2024    [135.0]
2025    [135.0]
2026    [130.0]
Name: cost_cap_limit_usd_m, dtype: object

### Q4. `f1_business` revenue components are a fixed split of the total

In [79]:
component_columns = ["race_promotion_fees_usd_m", "broadcast_media_usd_m", "sponsorship_usd_m", "other_revenue_usd_m"]

component_shares = f_one_business_df.set_index("season")[component_columns].div(f_one_business_df.set_index("season")["total_revenue_usd_m"], axis=0).round(3)
component_shares

,race_promotion_fees_usd_m,broadcast_media_usd_m,sponsorship_usd_m,other_revenue_usd_m
season,,,,
2010,0.360,0.340,0.160,0.140
2011,0.360,0.340,0.160,0.140
2012,0.360,0.340,0.160,0.140
2013,0.360,0.340,0.160,0.140
2014,0.360,0.340,0.160,0.140
2015,0.360,0.340,0.160,0.140
2016,0.360,0.340,0.160,0.140
2017,0.360,0.340,0.160,0.140
2018,0.360,0.340,0.160,0.140
2019,0.360,0.340,0.160,0.140
2020,0.554,0.523,0.247,0.215
2021,0.360,0.340,0.160,0.140
2022,0.360,0.340,0.160,0.140
2023,0.360,0.340,0.160,0.140
2024,0.360,0.340,0.160,0.140
2025,0.360,0.340,0.160,0.140
2026,0.360,0.340,0.160,0.140

In [80]:
components_minus_total = f_one_business_df.set_index("season")[component_columns].sum(axis=1) - f_one_business_df.set_index("season")["total_revenue_usd_m"]

components_minus_total[components_minus_total.abs() > 1]

season
2020    413.0
dtype: float64

### Q4. Viewer columns are placeholders or interpolated

In [81]:
viewers = f_one_business_df.set_index("season")[["us_avg_race_viewers_m", "global_avg_race_viewers_m", "drive_to_survive_viewers_m_est"]].copy()
viewers["global_viewers_change"] = viewers["global_avg_race_viewers_m"].diff()

viewers

,us_avg_race_viewers_m,global_avg_race_viewers_m,drive_to_survive_viewers_m_est,global_viewers_change
season,,,,
2010,0.55,70.0,0,NaN
2011,0.55,71.5,0,1.5
2012,0.55,73.0,0,1.5
2013,0.55,74.5,0,1.5
2014,0.55,76.0,0,1.5
2015,0.55,77.5,0,1.5
2016,0.55,79.0,0,1.5
2017,0.55,80.5,0,1.5
2018,0.55,82.0,0,1.5
2019,0.60,83.5,0,1.5
2020,0.55,72.2,13,-11.3
2021,0.95,91.5,25,19.3
2022,1.21,88.0,50,-3.5
2023,1.11,89.5,85,1.5
2024,1.10,91.0,60,1.5
2025,1.30,92.5,45,1.5
2026,1.45,94.0,30,1.5

### Q5. Does `prize_money_usd_m` follow this season's or last season's champion?
Rank of the champion's prize money within each season. Neither column settles it (see Q5 open question).

In [82]:
prize_check = constructor_df.sort_values(["team_name", "season"]).copy()
prize_check["was_champion_last_season"] = prize_check.groupby("team_name")["is_constructors_champion"].shift(1)
prize_check["prize_money_rank"] = prize_check.groupby("season")["prize_money_usd_m"].rank(ascending=False)

print("Champion this season, prize money rank:")
print(prize_check.loc[prize_check["is_constructors_champion"] == 1, "prize_money_rank"].value_counts())
print("Champion last season, prize money rank:")
print(prize_check.loc[prize_check["was_champion_last_season"] == 1, "prize_money_rank"].value_counts())

Champion this season, prize money rank:
prize_money_rank
1.0    4
2.0    3
3.0    3
Name: count, dtype: int64
Champion last season, prize money rank:
prize_money_rank
1.0    5
3.0    3
2.0    2
Name: count, dtype: int64